// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Entry 历史记录条目
 */
export class Entry {
    /**
     * Creates a new Entry instance.
     * @param {Partial<Entry>} [$$source = {}] - The source object to create the Entry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("source_text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_text"] = "";
        }
        if (!("translated_text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["translated_text"] = "";
        }
        if (!("source_lang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target_lang"] = "";
        }
        if (!("is_favorite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_favorite"] = false;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Entry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry(/** @type {Partial<Entry>} */($$parsedSource));
    }
}
