// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 桌面应用绑定服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as history$0 from "./internal/history/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "./internal/service/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "./internal/updater/models.js";

/**
 * CheckUpdate 检查是否有新版本
 * @returns {$CancellablePromise<updater$0.ReleaseInfo | null>}
 */
export function CheckUpdate() {
    return $Call.ByID(3935949939).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ClearCache 清空缓存
 * @returns {$CancellablePromise<void>}
 */
export function ClearCache() {
    return $Call.ByID(2357114119);
}

/**
 * ClearHistory 清空历史
 * @returns {$CancellablePromise<void>}
 */
export function ClearHistory() {
    return $Call.ByID(3526480461);
}

/**
 * Correct 通过同语言翻译获取拼写纠正建议
 * @param {string} text
 * @param {string} lang
 * @returns {$CancellablePromise<string>}
 */
export function Correct(text, lang) {
    return $Call.ByID(1780246280, text, lang);
}

/**
 * DeleteHistory 删除历史记录
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteHistory(id) {
    return $Call.ByID(3830904335, id);
}

/**
 * DownloadUpdate 下载并安装更新，完成后需重启应用
 * @param {string} downloadURL
 * @returns {$CancellablePromise<void>}
 */
export function DownloadUpdate(downloadURL) {
    return $Call.ByID(1964267315, downloadURL);
}

/**
 * GetCacheStats 获取缓存统计
 * @returns {$CancellablePromise<number>}
 */
export function GetCacheStats() {
    return $Call.ByID(1709152975);
}

/**
 * GetHistory 获取翻译历史
 * @param {number} offset
 * @param {number} limit
 * @param {string} keyword
 * @returns {$CancellablePromise<(history$0.Entry | null)[]>}
 */
export function GetHistory(offset, limit, keyword) {
    return $Call.ByID(258093614, offset, limit, keyword).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetHistoryCount 获取历史总数
 * @param {string} keyword
 * @returns {$CancellablePromise<number>}
 */
export function GetHistoryCount(keyword) {
    return $Call.ByID(1516555469, keyword);
}

/**
 * GetI18nFormats 获取支持的 i18n 格式列表
 * @returns {$CancellablePromise<string[]>}
 */
export function GetI18nFormats() {
    return $Call.ByID(2135701674).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetLanguages 获取支持的语言列表
 * @returns {$CancellablePromise<service$0.Language[]>}
 */
export function GetLanguages() {
    return $Call.ByID(3294138421).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetSettings 获取所有设置
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetSettings() {
    return $Call.ByID(3018893939).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetVersion 获取当前版本号
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(2729898890);
}

/**
 * IsHTTPAPIRunning HTTP API 是否运行中
 * @returns {$CancellablePromise<boolean>}
 */
export function IsHTTPAPIRunning() {
    return $Call.ByID(4147246689);
}

/**
 * IsMCPServerRunning MCP Server 是否运行中
 * @returns {$CancellablePromise<boolean>}
 */
export function IsMCPServerRunning() {
    return $Call.ByID(863184500);
}

/**
 * PlayTTS 获取 TTS 语音（返回 base64 编码）
 * @param {string} text
 * @param {string} lang
 * @returns {$CancellablePromise<string>}
 */
export function PlayTTS(text, lang) {
    return $Call.ByID(3435734397, text, lang);
}

/**
 * SetProxy 设置代理并保存配置
 * @param {string} proxyURL
 * @returns {$CancellablePromise<void>}
 */
export function SetProxy(proxyURL) {
    return $Call.ByID(733066694, proxyURL);
}

/**
 * SetSetting 设置配置
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetSetting(key, value) {
    return $Call.ByID(95120710, key, value);
}

/**
 * StartHTTPAPI 启动 HTTP API
 * @returns {$CancellablePromise<void>}
 */
export function StartHTTPAPI() {
    return $Call.ByID(1891741918);
}

/**
 * StartMCPServer 启动 MCP Server
 * @returns {$CancellablePromise<void>}
 */
export function StartMCPServer() {
    return $Call.ByID(1373145033);
}

/**
 * StopHTTPAPI 停止 HTTP API
 * @returns {$CancellablePromise<void>}
 */
export function StopHTTPAPI() {
    return $Call.ByID(1410261534);
}

/**
 * StopMCPServer 停止 MCP Server
 * @returns {$CancellablePromise<void>}
 */
export function StopMCPServer() {
    return $Call.ByID(56454409);
}

/**
 * ToggleFavorite 切换收藏
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function ToggleFavorite(id) {
    return $Call.ByID(1461788062, id);
}

/**
 * Translate 翻译文本（skipHistory: 自动翻译时跳过历史记录）
 * @param {string} text
 * @param {string} target
 * @param {string} source
 * @param {boolean} skipHistory
 * @returns {$CancellablePromise<service$0.TranslateResult | null>}
 */
export function Translate(text, target, source, skipHistory) {
    return $Call.ByID(1964803128, text, target, source, skipHistory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * TranslateI18nContent 翻译 i18n 内容（支持多种格式）
 * @param {string} content
 * @param {string[]} targetLangs
 * @param {string} sourceLang
 * @param {string} format
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function TranslateI18nContent(content, targetLangs, sourceLang, format) {
    return $Call.ByID(2159285145, content, targetLangs, sourceLang, format).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

// Private type creation functions
const $$createType0 = updater$0.ReleaseInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = history$0.Entry.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = service$0.Language.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = service$0.TranslateResult.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
