// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Language 语言信息
 */
export class Language {
    /**
     * Creates a new Language instance.
     * @param {Partial<Language>} [$$source = {}] - The source object to create the Language.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Language instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Language}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Language(/** @type {Partial<Language>} */($$parsedSource));
    }
}

/**
 * TranslateResult 翻译结果
 */
export class TranslateResult {
    /**
     * Creates a new TranslateResult instance.
     * @param {Partial<TranslateResult>} [$$source = {}] - The source object to create the TranslateResult.
     */
    constructor($$source = {}) {
        if (!("translated" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["translated"] = "";
        }
        if (!("source_lang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target_lang"] = "";
        }
        if (!("cached" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cached"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslateResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TranslateResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranslateResult(/** @type {Partial<TranslateResult>} */($$parsedSource));
    }
}
